import { Product, Category, Branch, Offer, HomepageCMS } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-cakes', name: 'Cakes', icon: '🎂', description: 'Handcrafted celebration cakes made fresh daily', displayOrder: 1, enabled: true },
  { id: 'cat-pastries', name: 'Pastries', icon: '🍰', description: 'Single-serving slice perfections', displayOrder: 2, enabled: true },
  { id: 'cat-breads', name: 'Breads', icon: '🍞', description: 'Freshly baked artisanal breads & sourdoughs', displayOrder: 3, enabled: true },
  { id: 'cat-puffs', name: 'Puffs & Rolls', icon: '🥐', description: 'Flaky golden pastries & savory rolls', displayOrder: 4, enabled: true },
  { id: 'cat-snacks', name: 'Snacks & Chaats', icon: '🌶️', description: 'Hot spicy bakery snacks & evening chaats', displayOrder: 5, enabled: true },
  { id: 'cat-cookies', name: 'Cookies', icon: '🍪', description: 'Crunchy butter cookies & rusks', displayOrder: 6, enabled: true },
  { id: 'cat-beverages', name: 'Beverages', icon: '☕', description: 'Fresh brews, teas, and cold delights', displayOrder: 7, enabled: true },
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-namakkal-main',
    name: 'Namakkal Main Branch',
    address: '1, Salem Road, Namakkal - 637001',
    phone: '+91 99426 45000',
    email: 'namakkal@satheeshbakery.com',
    googleMapLink: 'https://maps.google.com/?q=Namakkal',
    openingHours: '07:00 AM',
    closingHours: '10:30 PM',
    isOpen: true,
    isMain: true,
    managerName: 'Satheesh Kumar',
  },
  {
    id: 'branch-rasipuram',
    name: 'Rasipuram Branch',
    address: '45, Bazaar Street, Rasipuram - 637408',
    phone: '+91 99426 45000',
    email: 'rasipuram@satheeshbakery.com',
    googleMapLink: 'https://maps.google.com/?q=Rasipuram',
    openingHours: '08:00 AM',
    closingHours: '10:00 PM',
    isOpen: true,
    managerName: 'Rajesh Ram',
  },
  {
    id: 'branch-tiruchengode',
    name: 'Tiruchengode Express',
    address: '12, Sankari Road, Tiruchengode - 637211',
    phone: '+91 99426 45000',
    email: 'tiruchengode@satheeshbakery.com',
    googleMapLink: 'https://maps.google.com/?q=Tiruchengode',
    openingHours: '08:00 AM',
    closingHours: '10:00 PM',
    isOpen: true,
    managerName: 'Priya Dharshini',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-choc-truffle',
    name: 'Signature Chocolate Truffle Cake',
    displayName: 'Royal Chocolate Truffle (1 kg)',
    description: 'Layered rich dark chocolate ganache cake crafted with Dutch cocoa, Belgian dark chocolate glaze, and delicate chocolate curls.',
    ingredients: ['Dark Dutch Cocoa', 'Belgian Chocolate', 'Fresh Dairy Cream', 'Wheat Flour', 'Butter', 'Vanilla Extract'],
    price: 750,
    offerPrice: 680,
    categoryId: 'cat-cakes',
    rating: 4.9,
    reviewCount: 142,
    featured: true,
    bestSeller: true,
    isNewArrival: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80'
    ],
    coverImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 5,
      spice: 0,
      softness: 5,
      crunchiness: 1,
      temperature: 'cold',
      diet: 'eggless',
      prepTime: 40,
      occasion: ['birthday', 'party', 'anniversary', 'kids'],
      tags: ['bestseller', 'premium', 'chocolate', 'eggless'],
    },
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-veg-puff',
    name: 'Classic Hot Spicy Veg Puff',
    displayName: 'Flaky Hot Veg Puff',
    description: 'Crispy multi-layered puff pastry filled with hot spiced potato, green peas, curry leaves, and aromatic spices.',
    ingredients: ['Whole Wheat Flour', 'Potatoes', 'Green Peas', 'Garam Masala', 'Butter', 'Curry Leaves'],
    price: 35,
    offerPrice: 30,
    categoryId: 'cat-puffs',
    rating: 4.8,
    reviewCount: 310,
    featured: true,
    bestSeller: true,
    isNewArrival: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 0,
      spice: 4,
      softness: 2,
      crunchiness: 5,
      temperature: 'hot',
      diet: 'eggless',
      prepTime: 10,
      occasion: ['teaTime', 'snack', 'quickBite', 'breakfast'],
      tags: ['bestseller', 'spicy', 'hot', 'crispy', 'eggless'],
    },
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-chicken-puff',
    name: 'Fiery Chicken Pepper Puff',
    displayName: 'Chicken Pepper Puff',
    description: 'Golden puff filled with succulent roasted pepper chicken cooked with crushed black pepper and onions.',
    ingredients: ['Chicken Tenderloin', 'Black Pepper', 'Onion', 'Flaky Pastry Dough', 'Refined Butter'],
    price: 55,
    offerPrice: 48,
    categoryId: 'cat-puffs',
    rating: 4.9,
    reviewCount: 280,
    featured: true,
    bestSeller: true,
    isNewArrival: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 0,
      spice: 5,
      softness: 2,
      crunchiness: 5,
      temperature: 'hot',
      diet: 'egg',
      prepTime: 12,
      occasion: ['teaTime', 'snack', 'quickBite'],
      tags: ['bestseller', 'spicy', 'hot', 'chicken'],
    },
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-red-velvet',
    name: 'Red Velvet Cream Cheese Pastry',
    displayName: 'Red Velvet Pastry Slice',
    description: 'Moist red velvet sponge slice layered with pure vanilla bean cream cheese frosting and fine red cocoa crumbs.',
    ingredients: ['Cocoa Powder', 'Cream Cheese', 'Vanilla Bean Extract', 'Butter', 'Flour'],
    price: 120,
    offerPrice: 105,
    categoryId: 'cat-pastries',
    rating: 4.7,
    reviewCount: 95,
    featured: true,
    bestSeller: false,
    isNewArrival: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 4,
      spice: 0,
      softness: 5,
      crunchiness: 1,
      temperature: 'cold',
      diet: 'eggless',
      prepTime: 15,
      occasion: ['party', 'kids', 'dessert'],
      tags: ['new', 'eggless', 'redvelvet'],
    },
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-sourdough',
    name: 'Artisanal Garlic Herb Sourdough',
    displayName: 'Garlic Herb Sourdough Loaf',
    description: 'Slow-fermented 36-hour sourdough bread infused with roasted garlic confit, rosemary, and extra virgin olive oil.',
    ingredients: ['Natural Sourdough Starter', 'Organic Wheat Flour', 'Roasted Garlic', 'Fresh Rosemary', 'Sea Salt'],
    price: 180,
    offerPrice: 160,
    categoryId: 'cat-breads',
    rating: 4.8,
    reviewCount: 64,
    featured: false,
    bestSeller: false,
    isNewArrival: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 0,
      spice: 1,
      softness: 4,
      crunchiness: 3,
      temperature: 'room',
      diet: 'vegan',
      prepTime: 20,
      occasion: ['breakfast', 'teaTime', 'healthy'],
      tags: ['new', 'healthy', 'vegan', 'bread'],
    },
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-paneer-roll',
    name: 'Paneer Tikka Roll',
    displayName: 'Spicy Paneer Tikka Roll',
    description: 'Fresh tandoori marinated paneer cubes wrapped in soft layered paratha with mint chutney and crunchy bell peppers.',
    ingredients: ['Fresh Paneer', 'Tandoori Masala', 'Whole Wheat Wrap', 'Mint Chutney', 'Capsicum'],
    price: 85,
    offerPrice: 75,
    categoryId: 'cat-snacks',
    rating: 4.7,
    reviewCount: 112,
    featured: true,
    bestSeller: false,
    isNewArrival: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 0,
      spice: 4,
      softness: 4,
      crunchiness: 2,
      temperature: 'hot',
      diet: 'eggless',
      prepTime: 15,
      occasion: ['snack', 'quickBite', 'teaTime'],
      tags: ['spicy', 'paneer', 'eggless', 'hot'],
    },
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-almond-cookies',
    name: 'Almond Butter Cookies (250g)',
    displayName: 'Almond Butter Cookies Pack',
    description: 'Melt-in-your-mouth slow baked butter cookies loaded with toasted California almond slivers and cardamom.',
    ingredients: ['Pure Cow Ghee', 'Sliced Almonds', 'Refined Wheat Flour', 'Powdered Sugar', 'Cardamom'],
    price: 190,
    offerPrice: 175,
    categoryId: 'cat-cookies',
    rating: 4.9,
    reviewCount: 156,
    featured: false,
    bestSeller: true,
    isNewArrival: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 3,
      spice: 0,
      softness: 1,
      crunchiness: 5,
      temperature: 'room',
      diet: 'eggless',
      prepTime: 5,
      occasion: ['teaTime', 'festival', 'kids'],
      tags: ['bestseller', 'cookies', 'eggless', 'crunchy'],
    },
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now(),
  },
  {
    id: 'prod-cold-coffee',
    name: 'Caramel Hazelnut Cold Coffee',
    displayName: 'Creamy Hazelnut Cold Coffee',
    description: 'Chilled espresso blended with creamy whole milk, housemade caramel syrup, and crushed hazelnut topping.',
    ingredients: ['Arabica Espresso', 'Full Cream Milk', 'Caramel Drizzle', 'Hazelnut Extract'],
    price: 110,
    offerPrice: 99,
    categoryId: 'cat-beverages',
    rating: 4.8,
    reviewCount: 78,
    featured: false,
    bestSeller: false,
    isNewArrival: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80',
    ],
    coverImage: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80',
    metadata: {
      sweetness: 4,
      spice: 0,
      softness: 5,
      crunchiness: 0,
      temperature: 'cold',
      diet: 'eggless',
      prepTime: 5,
      occasion: ['teaTime', 'quickBite', 'party'],
      tags: ['new', 'beverage', 'cold', 'coffee'],
    },
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  }
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'offer-weekend-cake',
    title: 'Weekend Festive Special',
    description: 'Get 15% OFF on all Signature Celebration Cakes & Truffles!',
    discountPercentage: 15,
    bannerUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-01-01',
    startTime: '00:00',
    endDate: '2027-12-31',
    endTime: '23:59',
    enabled: true
  },
  {
    id: 'offer-2',
    title: 'Weekend Special',
    description: 'Get 20% off on all signature cakes this weekend.',
    discountPercentage: 20,
    bannerUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80',
    startDate: '2026-01-01',
    startTime: '00:00',
    endDate: '2027-12-31',
    endTime: '23:59',
    enabled: true,
  }
];

export const INITIAL_CMS: HomepageCMS = {
  banners: [
    {
      id: 'banner-1',
      desktopImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1920&q=80',
      mobileImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
      title: 'Artisanal Bakes, Crafted Daily',
      subtitle: 'Experience the magic of freshly baked premium pastries.',
      buttonText: 'View Digital Menu',
      buttonLink: '/menu',
      enabled: true,
      displayOrder: 1,
    }
  ],
  announcement: {
    id: 'ann-1',
    title: '🎉 Welcome to Satheesh Bakery Digital!',
    description: 'Enjoy 10% instant discount on your first pickup order. Use code: FRESHSTART',
    buttonText: 'Order Pickup',
    buttonLink: '/menu',
    enabled: true,
    priority: 1,
  },
  featuredCategoryIds: ['cat-cakes', 'cat-pastries', 'cat-puffs', 'cat-snacks'],
  featuredProductIds: ['prod-choc-truffle', 'prod-veg-puff', 'prod-chicken-puff', 'prod-red-velvet'],
  bestSellerProductIds: ['prod-choc-truffle', 'prod-veg-puff', 'prod-chicken-puff', 'prod-almond-cookies'],
};
